### ISSUE TITLE
Image Board YAML

### ISSUE THREAD

**Issue by RogueSensei** [RogueSensei/Bot_Wilson#52]
# Image Board YAML
Add a YAML for use in the `Images()` class
### Sample:
```yml
---
board: imgur
   url: main url
   img: image url
```

**Comment by RogueSensei** [comment]
```yml
board:
    url:
   img_url:
```
